---
title: "Background for Data Science"
output: html_notebook
---

# Overview
* This special background module brings people up to speed before we get into the actual course material
* Summary
    - Sets
    - Probability
    - Random Variable
    - Statistics
    - Lenear algebra
    - Data structures
    - Algorithms
    - Computer programming in Python
* Please work on all exercises for maximum benefit

# Set
Sets are used to identify sample spaces.  Sample spaces can also be refered to as the universe of outcomes.  
Sets are made up of elements. Sets have subsets.

If we think of the universe as all possible outcomes, then and event is an element in the set.

The simple example of a sample space is the result of a coin toss: heads or tails.
This is similar to making a decision: yes or no.  Note that the sample space contains all possible
outcomes.  Your age is not a sample set, but all possible values that your age could be is a sample space.
All colors offered by a paint company is a sample space.  The color you select is an element in that 
sample space.  An element is a set of one element.  The sample space is a set of all the elements.

The idea of a sample space is important because the possible results of an experiment are a sample space.
The experementer starts out with observational units.  Observations are take from those observational units.
The observations should be contained in the sample space.  
* An observational unit: a coin
* The experement: Flip the coin
* The set of outcomes: Heads or Tails.

A sample space can be a  set of discrete outcomes or a continous outcome.  In the case of
a continous outcome, we talk about intervals instead of a single number.  For example, we can 
say it will rain between 2 to 4 inches tomorrow.  We don't predict three inches because it will never 
be exactly three inches. 

Mathematical operations on sample spaces are union, intersection and compliments.  The idea of mutually
excluse sets is important.  Mutually exclusive is similar to disjoint.

There are three simple ideas related to the sets we will work with that allow us use the next idea, probability.

* The empty set:  The concept that the union of any set with the empty set is that same set.
* Complement: The complement of a set unioned with that element is the sample set. This is the same as saying that 
any number plus zero is that same number.  5 + 0 = 5.

* Closure: If we take different elements and union them together, their union will also be part of the sample set. 
Their complement is also a  of the the sample set.  
This means that each set needs to have all the possible combinations of unions in the set. So if you have a 
set with elements A and B, then you also need the subset A union B and the complement of A union B as well as
the complements of A and B. The sets that we work work with can never have less than two subsets.
Try to describe a set with the following number of subsets:
* 2
* 4
* 8
* 16
The number of possible subsets of a finite set have to be a power of 2.  

# Probability
From a mathematical perspective, propability is just a function that takes a set or element of a set as
the input and produces a number between 0 and 1.  The probability of the empty set is 0 and the probability
of the whole set is 1. You can always break down the probability of a set into the sum of its mutually exclusive 
elements.  

For example, the set of outcomes when you 
flip a coin is heads or tails.  The probability of the either heads or tails is one.  The
probability of heads plus the probability of tails is one because the event of heads is the complement of the
event of tails.  They are also mutually exclusive events.

When the outcome is a interval or ratio number, then we assign probabilities to intervals.  
What is the chance it will rain more than one inch tomorrow?
What is the chance your investment rate of return will be between 4 and 8 percent?

The probility of the complement of an event is 1 - the probability of that event.  The use of complements 
is very useful in calculating probabilities.  For example, the probability of and event happening one or more 
times is the 1 - the probability of the event never happening.  The probability of a number being greater than 2 
or less than negative 2 is 1 - the probability of the number being between -2 AND + 2.

There are some mathematical equalities and inequalities needed for probability.

* P(A): Probability of the event A
* P(B): Proability of the event B
*$P(B \cup B)$

*$P(B \cup A)4/4$
 ## Random Variable  

y* Set Theory
* Random variable
* Counting
* Probability of events
* Independent random variables
* Coin Toss examples
* Probability distributions
* Probability inequalities
The set of outcomes depends on how the outcome is measured.  This is because natural events have to be  
converted to data: nominal, ordinal, interval, ratio.
For example: Will it snow tomorrow?  We could measure the sample space as yes or no: a bernoili variable.  Or we could 
record the number of inches: an integer. 

Another example is tire failure. You can measure the number of flat tires per 100,000 miles.  Or you can measure the
number of miles needed on average to experience 3 flat ties.  
