library(quantmod)
library(tidyquant)
library(data.table)
library(glue)
library(tidytext)
library(tidyquant)
library(tidyverse)
library(magrittr)
library(lubridate)
library(ggplot2)
library(lucr)
library(tidyjson)

#devtools::install_github("sailthru/tidyjson")
library(tidyjson)
