---
title: "Quiz for Basic Statistics"
output: html_notebook
---


1. (Types of Data) A data set contains the activity a merchant as selling fruits and vegetables, Embroider, transportaion
or services.  This type of data is:

* A. Categorical
* B. Discrete and Numerical
* C. Continous and Numerical
* D. Ordinal

2. A questionaire asks respondents to mark their opinion as strongly disagree, disagree, neutral, agree or strongly agree.
This type of data is:

*A. Categorical and nominal
*B. Discrete and Ordinal
*C. Interval 
*D. Ratio

3. Question two is coded as 
- strongly disagree: -2
- disagree: -1
- neutral: 0
- agree: 1
- strongly agree: 2
Now the data ranges from -2 to +2.  It it now interval data?

*A. It could be interval if the effort needed to change someone opinion form -2 to -1 is similar to the effort needed 
to change someones opinion from 1 to 2. The same must be true for all other pairs of intervals.
*B. The data is ordinal but can never be treated as interval.


4. If the survey in question 2 has 15 questions and the questions are grouped in groups of 5 questions each and 
the sum of the responses from -2 to +2 are used instead of the individual question responses, the resulting three
number for each respondent will be:

*A. Impossible to interpret and is a bad idea.
*B. Have some characteristics of continous data because there will now be thousands of possible values ranging
from -10 to +10.

5. One way to categorize data is qualitative or quantitative. Which are of following are qualitative?

*A. Nominal Data
*B. Ordinal Data
*C. Interval Data
*D. Ratio Data

